# docker-compose.yml
# Removido: version: '3.8' (obsoleto)

services:
  # PHP-FPM Service for Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.app # Use the combined Dockerfile
      target: app_final # Specify the target build stage for the 'app' service
    container_name: calculinha_app
    depends_on:
      - db
      - redis
    # Expose port 9000 for Nginx to communicate with PHP-FPM
    ports:
      - "9000:9000"
    # Environment variables for the Laravel application
    env_file:
      - .env.prod
    environment:
      DB_HOST: db

  # Nginx Service to serve the application
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.app # Use the combined Dockerfile
      target: nginx_final # Specify the target build stage for the 'nginx' service
    container_name: calculinha_nginx
    depends_on:
      - app # Nginx depends on app for runtime, but build-time dependency is handled by multi-stage Dockerfile
    # Map host port 8000 to container port 80
    ports:
      - "8000:80"

  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: calculinha_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis Service for caching and queues
  redis:
    image: redis:7-alpine
    container_name: calculinha_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

# Define named volumes for data persistence
volumes:
  db_data:
  redis_data:
