/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.telescope": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "debugbar.queries.explain": [],
    "sanctum.csrf-cookie": [],
    "welcome": [],
    "student.login": [],
    "teacher.login": [],
    "student.login.post": [],
    "teacher.login.post": [],
    "student.register": [],
    "teacher.register": [],
    "student.register.post": [],
    "teacher.register.post": [],
    "student.dashboard": [],
    "student.join": [],
    "student.room": [
        {
            "name": "room",
            "required": true,
            "binding": "id"
        }
    ],
    "student.answer": [],
    "student.retry": [
        {
            "name": "module",
            "required": true,
            "binding": "id"
        }
    ],
    "quiz.show": [
        {
            "name": "room",
            "required": true,
            "binding": "id"
        },
        {
            "name": "module",
            "required": true,
            "binding": "id"
        }
    ],
    "teacher.dashboard": [],
    "rooms.index": [],
    "rooms.create": [],
    "rooms.store": [],
    "rooms.edit": [
        {
            "name": "room",
            "required": true
        }
    ],
    "rooms.update": [
        {
            "name": "room",
            "required": true,
            "binding": "id"
        }
    ],
    "rooms.destroy": [
        {
            "name": "room",
            "required": true,
            "binding": "id"
        }
    ],
    "rooms.reorder-modules": [
        {
            "name": "room",
            "required": true,
            "binding": "id"
        }
    ],
    "modules.index": [],
    "modules.create": [],
    "modules.store": [],
    "modules.edit": [
        {
            "name": "module",
            "required": true
        }
    ],
    "modules.update": [
        {
            "name": "module",
            "required": true,
            "binding": "id"
        }
    ],
    "modules.destroy": [
        {
            "name": "module",
            "required": true,
            "binding": "id"
        }
    ],
    "modules.reorder-activities": [
        {
            "name": "module",
            "required": true,
            "binding": "id"
        }
    ],
    "activities.index": [],
    "activities.create": [],
    "activities.store": [],
    "activities.edit": [
        {
            "name": "activity",
            "required": true
        }
    ],
    "activities.update": [
        {
            "name": "activity",
            "required": true,
            "binding": "id"
        }
    ],
    "activities.destroy": [
        {
            "name": "activity",
            "required": true,
            "binding": "id"
        }
    ],
    "register": [],
    "login": [],
    "password.email": [],
    "password.store": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
